"""Common pydantic data models for the API request/responses"""

from typing import Literal, Optional, List, Dict, Any, Union
import time
import bleach
import shortuuid
import copy
from pydantic import BaseModel, Field, validator, root_validator

from utils.strings import encode_json_strings, decode_json_strings


def generate_random_id():
    return shortuuid.random()


class ErrorResponse(BaseModel):
    object: str = 'error'
    message: str
    code: int


class UsageInfo(BaseModel):
    prompt_tokens: int = 0
    total_tokens: int = 0
    completion_tokens: Optional[int] = 0


Role = Literal['system', 'user', 'assistant', 'tool']


class Function(BaseModel):
    """Function definition"""

    name: str
    description: str
    parameters: Any


class FunctionTool(BaseModel):
    """Function Tool definition"""

    type: str
    function: Function


class ToolCallRequest(BaseModel):
    """Tool call request generated by the LLM model"""

    id: str = Field(default_factory=lambda: f'call_{generate_random_id()}')
    type: str
    function: Any

    def serialize_tool_payload(self) -> Any:
        if self.type == 'function':
            return {'recipient_name': f'functions.{self.function["name"]}', 'parameters': self.function['arguments']}
        else:
            return None


class ToolCallResponse(BaseModel):
    """Tool call response send by client"""

    tool_call_id: str
    role: str
    name: str
    content: Any

    def serialize_content(self) -> None:
        if self.content is not None:
            # Try to encode objects to json string
            self.content = encode_json_strings(self.content)


class ChatMessage(BaseModel):
    role: Role
    content: Optional[str | None]
    tool_calls: Optional[List[ToolCallRequest]] = None

    @validator('role')
    def validate_role(cls, value):
        """Field validator function to validate values of the field role"""
        value = bleach.clean(value, strip=True)
        valid_roles = {'user', 'assistant', 'system', 'tool'}
        if value.lower() not in valid_roles:
            raise ValueError("Role must be one of 'user', 'assistant', 'system', or 'tool'")
        return value.lower()

    @validator('content')
    def sanitize_content(cls, v):
        """Field validator function to santize user populated fields from HTML"""
        if v is None:
            return v
        return bleach.clean(v, strip=True)

    @root_validator(pre=True)
    def check_content_or_tool_calls(cls, values):
        """Root validator to ensure either content or tool_calls is provided, but not both being None"""
        content, tool_calls = values.get('content'), values.get('tool_calls')
        if content is None and tool_calls is None:
            raise ValueError('Either content or tool_calls must be provided.')
        return values

    def serialize_content(self) -> None:
        if self.content is not None:
            # Try to encode objects to json string
            self.content = encode_json_strings(self.content)
        elif self.tool_calls is not None:
            tool_calls = [tool.serialize_tool_payload() for tool in self.tool_calls if tool.serialize_tool_payload() is not None]
            self.content = encode_json_strings({'tool_uses': tool_calls})


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage | ToolCallResponse]
    tools: Optional[List[FunctionTool]] = None
    temperature: Optional[float] = 0.7
    top_p: Optional[float] = 1.0
    top_k: Optional[int] = -1
    max_tokens: Optional[int] = 1024
    stop: Optional[Union[str, List[str]]] = None
    stream: Optional[bool] = False
    repetition_penalty: Optional[float] = 1
    length_penalty: Optional[float] = 1.0
    seed: Optional[int] = 1

    @validator('messages')
    def validate_messages(cls, v):
        """Field validator function to check valid message turns"""
        if v is None or len(v) == 0:
            raise ValueError('Chat messages can not be none or empty')
        else:
            if v[0].role not in ['user', 'system']:
                raise ValueError('Chat messages should start with either "system" or "user"')

            user_turn_indices = [i for i in range(len(v)) if v[i].role == 'user']
            if any([v[i + 1].role != 'assistant' for i in user_turn_indices if i < len(v) - 1]):
                raise ValueError('Each "user" message must be followed by an "assistant" response')

            assistant_turn_indices = [i for i in range(len(v)) if v[i].role == 'assistant']
            if any([v[i + 1].role not in ['user', 'tool'] for i in assistant_turn_indices]):
                raise ValueError('Each "assistant" message must be followed by either "user" or "tool" response')

            tool_calls_indices = [i for i in range(len(v)) if v[i].role == 'assistant' and v[i].tool_calls is not None]
            if any([v[i + 1].role != 'tool' for i in tool_calls_indices if i < len(v) - 1]):
                raise ValueError('Each "assistant" message with "tool_calls" must be followed by an "tool" response')

            # for i in tool_calls_indices:
            #     if i < len(v) - 1:
            #         call_ids = [call.id for call in v[i].tool_calls]
            #         response_ids = [res.tool_call_id for res in v[i + 1]]
            #         if response_ids != call_ids:
            #             missing_call_ids = set(response_ids).difference(call_ids)
            #             missing_ids_str = ', '.join(map(str, missing_call_ids))
            #             raise ValueError(f'Each "tool_calls" must be followed by an "tool" with corresponding "tool_call_id" matching, got missing "tool_call_id" in response: {missing_ids_str}')

            return v
            # else:
            #     if not all([msg.role == 'user' for msg in v[start_idx::2]]) or not all([msg.role == 'assistant' for msg in v[start_idx + 1 :: 2]]):
            #         raise ValueError('Chat messages should start with either "system" or "user", then followed by "assistant", and alternating (user/assistant/...)')
            #     else:
            #         return v

    # def merge_messages(self) -> None:
    #     """Merge multiple consecutive tool responses into a single message"""
    #     start_idx = None
    #     end_idx = None
    #     i = 0
    #     n = len(self.messages)
    #     while i < n:

    #         if self.messages[i].role == 'tool':
    #             start_idx = i
    #             # delta_tool_messages = [self.messages[i]]
    #             for j in range(n - start_idx):
    #                 if self.messages[j].role == 'tool':
    #                     end_idx = j
    #                 else:
    #                     break

    #             if end_idx:
    #                 delta_tool_responses = copy.deepcopy(self.messages[start_idx : end_idx + 1])
    #                 self.messages[start_idx] = ChatMessage(role='tool', content=delta_tool_responses)

    #                 for del_idx in range(start_idx + 1, end_idx + 1):
    #                     self.messages.pop(del_idx)
    #             else:
    #                 self.messages[start_idx] = ChatMessage(role='tool', content=[self.messages[start_idx]])
    #         i += 1


class ChatCompletionResponseChoice(BaseModel):
    index: int
    message: ChatMessage
    logprobs: Optional[List[float]] = None
    finish_reason: Optional[Literal['stop', 'length']] = 'stop'


class ChatCompletionResponse(BaseModel):
    id: str = Field(default_factory=lambda: f'chatcmpl-{generate_random_id()}')
    object: str = 'chat.completion'
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: List[ChatCompletionResponseChoice]
    usage: Optional[UsageInfo] = None


class DeltaMessage(BaseModel):
    role: Optional[str] = None
    content: Optional[str] = None


class ChatCompletionResponseStreamChoice(BaseModel):
    index: int
    delta: DeltaMessage
    logprobs: Optional[List[float]] = None
    finish_reason: Optional[Literal['stop', 'length']] = 'stop'


class ChatCompletionStreamResponse(BaseModel):
    id: str = Field(default_factory=lambda: f'chatcmpl-{generate_random_id()}')
    object: str = 'chat.completion.chunk'
    created: int = Field(default_factory=lambda: int(time.time()))
    model: str
    choices: List[ChatCompletionResponseStreamChoice]


class EmbeddingRequest(BaseModel):
    model: str
    input: Union[str, List[str]]
    encoding_format: Optional[str] = 'float'


class Embedding(BaseModel):
    index: int
    embedding: List[float]
    object: Optional[str] = 'embedding'


class EmbeddingResponse(BaseModel):
    data: List[Embedding]
